export default {
  splash: 'splash',
  login: 'login',
  register: 'register',
  forgotpass: 'forgetpassword',
  home: 'Home',
  home1: 'Home1',
  tabRoutes: 'TabRoutes',
  maincart: 'MainCart',
  profile: 'Profile',
  mall: 'mall',
  localmaall: 'LocalMall',
  foodDetail: 'Food Details',
  Checkout: 'checkout',
};
