export default {
  splash: 'splash',
  login: 'login',
  register: 'register',
  forgotpass: 'forgetpassword',
  home: 'Home',
  home1: 'Home1',
  tabRoutes: 'TabRoutes',
  maincart: 'MainCart',
  profile: 'Profile',
  mall: 'mall',
  localmaall: 'LocalMall',
  foodDetail: 'Food Details',
  newfoodDetail: 'Best Food Details',

  Checkout: 'checkout',
  myorder: 'My Orders',
  account: 'Account',
  camera: 'Camera',
  qrcode: 'QrCode',
  deviceinfo: 'Device Info',
  myTabsView: 'MyTabsView',
  restaurant: 'Restaurants',
  notification: 'Notification',
  chatBot: 'chatBot',
  userChat: 'UserChat',
  userOneChat: 'UserOneChat',
  foodiMart: 'FoodiMart',
  foodiMartDetails: 'FoodiMartDetails',
  formikLogin: 'Formik Login',
  lineChart: 'Line Chart',
  trackOrder: 'Track Order',
  foodiMartDetails1: 'FoodiMartDetails1',
};
